apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: easy
  name: easy-full-access
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf1-easy-access
  namespace: easy
subjects:
- kind: User
  name: ctf1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: easy-full-access
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: medium
  name: medium-limited-access
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list"]  # Assuming you want to allow creation, listing, and deletion of pods
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf1-medium-access
  namespace: medium
subjects:
- kind: User
  name: ctf1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: medium-limited-access
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-listing-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ctf1-namespace-listing-binding
subjects:
- kind: User
  name: ctf1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespace-listing-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: medium
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: medium
subjects:
- kind: ServiceAccount
  name: default
  namespace: medium
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

